#!/bin/bash

# RAG (Retrieval-Augmented Generation) script for beavr-bot codebase
# This script helps document the code structure and names for AI assistance

echo "=== BEAVR-BOT CODE STRUCTURE DOCUMENTATION ==="
echo "Generated on: $(date)"
echo ""

echo "=== MAIN PACKAGE STRUCTURE ==="
echo "src/beavr/teleop/ - Main teleop package"
echo "├── components/ - Core teleop components"
echo "│   ├── component.py - Base Component class (ABC)"
echo "│   ├── detector/ - Hand/keypoint detection components"
echo "│   ├── environment/ - Robot environment components"
echo "│   ├── operators/ - Data processing operators"
echo "│   ├── recorders/ - Data recording components"
echo "│   ├── sensors/ - Sensor interface components"
echo "│   └── visualizers/ - Visualization components"
echo "├── configs_teleop/ - Configuration files"
echo "├── controllers/ - Robot control interfaces"
echo "├── interfaces/ - Robot interface abstractions"
echo "├── robot/ - Robot-specific implementations"
echo "├── ros_links/ - ROS integration"
echo "├── samplers/ - Data sampling components"
echo "└── utils/ - Utility functions"
echo ""

echo "=== KEY COMPONENTS ==="
echo "Component (ABC) - Base class for all teleop components"
echo "TransformHandPositionCoords - Hand position coordinate transformation"
echo "ZMQKeypointSubscriber - ZMQ-based keypoint data subscriber"
echo "ZMQPublisherManager - ZMQ publisher management"
echo "FrequencyTimer - Frequency-based timing control"
echo ""

echo "=== CONFIGURATION FILES ==="
echo "xarm7_right_config.py - XArm7 right arm configuration"
echo "bimanual_xarm_config.py - Bimanual XArm configuration"
echo "constants_loader.py - Configuration constants loader"
echo ""

echo "=== UTILITY MODULES ==="
echo "vectorops.py - Vector operations (normalize, moving average)"
echo "network.py - Network utilities (ZMQ, TCP)"
echo "timer.py - Timing utilities"
echo "files.py - File handling utilities"
echo "handshake.py - Connection handshake utilities"
echo "images.py - Image processing utilities"
echo ""

echo "=== TEST STRUCTURE ==="
echo "tests/ - Test directory"
echo "├── components/ - Component tests"
echo "├── integration/ - Integration tests"
echo "├── robot/ - Robot-specific tests"
echo "└── debugging/ - Debugging utilities"
echo ""

echo "=== ASSETS ==="
echo "assets/urdf/ - Robot URDF files"
echo "├── allegro_hand_description/ - Allegro hand models"
echo "├── franka_description/ - Franka robot models"
echo "├── xarm7/ - XArm7 robot models"
echo "└── objects/ - Object models"
echo ""

echo "=== IMPORTANT PATTERNS ==="
echo "1. All components inherit from Component (ABC)"
echo "2. Components use stream() method for main processing loop"
echo "3. ZMQ is used for real-time data streaming"
echo "4. Configuration uses draccus for argument parsing"
echo "5. Moving averages are used for data smoothing"
echo "6. Frequency timers control processing rates"
echo ""

echo "=== COMMON IMPORTS ==="
echo "from beavr.teleop.components import Component"
echo "from beavr.teleop.utils.vectorops import normalize_vector, moving_average"
echo "from beavr.teleop.utils.network import ZMQKeypointSubscriber, ZMQPublisherManager"
echo "from beavr.teleop.utils.timer import FrequencyTimer"
echo ""

echo "=== CONFIGURATION FLAGS ==="
echo "All testing/logging should have configuration flags to disable prints"
echo "Use config parameters to control debug output"
echo ""

echo "=== DOCUMENTATION ==="
echo "Code should be documented with useful comments"
echo "Separate documentation files for complex functionality"
echo "Maintain this rag.sh script for AI assistance"
echo ""

echo "=== ITERATIVE DEVELOPMENT ==="
echo "Test different modules separately"
echo "Focus on efficiency for real-time data streams"
echo "Prioritize maintainable code structure"
echo "" 