name: CI

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  pull_request:
    branches: [ main, feature/**, bugfix/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        env:
          HF_HUB_ENABLE_HF_TRANSFER: '1'
        run: |
          pytest -q


