name: Fast Tests

on:
  pull_request:
    branches: [ main, feature/**, bugfix/** ]

env:
  PYTHON_VERSION: "3.10"

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . --no-deps
      - name: Run fast tests
        run: pytest -q
