name: Full Tests

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:
    branches: [ main, develop ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/**"
      - "requirements.txt"

env:
  PYTHON_VERSION: "3.10"
  DOCKER_IMAGE_NAME: beavr/beavr-bot

jobs:
  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . --no-deps
      - name: Run tests
        run: pytest tests/ -v

  # build-docker:
  #   name: Build Docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build Docker image
  #       run: docker build -f docker/Dockerfile.user -t ${{ env.DOCKER_IMAGE_NAME }} .

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: [build-docker]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run integration tests
  #       run: make test-integration
